### ISSUE TITLE
Support windows

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/python-igraph-feedstock#10]
Once https://github.com/conda-forge/igraph-feedstock/pull/7 lands, it should be relatively straightforward, right?

**Comment by sodre** [comment]
@bollwyvl that is correct. I just have been short on time to work on that fix. I will gladly take/review a PR if you want to work on it.

**Comment by bollwyvl** [comment]
I hear you, my friend! Sorry if I came across as needy. Just lining up some
issues for justifying skipping a Windows build downstream.... Indeed,
py2cytoscape will be making igraph an optional dependency soon, but it's
likely worth doing anyway!

**Comment by vtraag** [comment]
The recent new release (0.8.0) is now available for Windows.
