### ISSUE TITLE
License violations

### ISSUE THREAD

**Issue by isuruf** [conda-forge/python-igraph-feedstock#22]
Please include the licenses of the package that igraph is using. I'll delete the 0.8.0 package soon.

**Comment by vtraag** [comment]
We are working on improving this. We are current backtracking all included code and necessary licences, and we will include it when we are done with that.

**Comment by isuruf** [comment]
Ping on this. Is this on master of python-igraph?

**Comment by vtraag** [comment]
We are still working on this. We have contacted a number of authors for parts that were not clearly licenced. Presumably we will be able to update  licences and provide appropriate references somewhere next week.

**Comment by isuruf** [comment]
Thanks @vtraag for the update.

**Comment by vtraag** [comment]
@isuruf We now provide an overview of all the licences for all source code/packages that are included/linked to by `igraph`, see PR https://github.com/igraph/igraph/pull/1340. We would like to release an updated version shortly that also includes these acknowledgements and licences properly. 

Is there any specific requirement for how to include this in the `python-igraph` feedstock or the `python-igraph` source tarball / wheels? Right now the `python-igraph` source tarball includes the file `COPYING`. Should that additionally contain essentially, additionally, the content of what we have now included in [`ACKNOWLEDGEMENTS.md`](https://github.com/igraph/igraph/blob/master/ACKNOWLEDGEMENTS.md)? Or can we include multiple licence files, one for `igraph` and the other for all dependencies? Any comment is welcome! We are certainly no experts in licencing issues.

**Comment by isuruf** [comment]
Thanks @vtraag and team for working for on this. Yes, we can include multiple license files.
```
license_file:
  - COPYING
  - ACKNOWLEDGEMENTS.md
```

**Comment by vtraag** [comment]
OK, great, I will include multiple licence files then.

We are now working towards making a new release (0.8.1). When that is out, I can properly update this feedstock to address this issue.

**Comment by vtraag** [comment]
@isuruf this should now be fixed in https://github.com/regro-cf-autotick-bot/python-igraph-feedstock/commit/11a8408cddf35bc219a2e8ed567e6fb721d8457b. Could you please double check whether this fixes the identified problem?
