### ISSUE TITLE
Reading GraphML files not enables

### ISSUE THREAD

**Issue by gclplp** [conda-forge/python-igraph-feedstock#32]
When try to read GraphML files I get the following error:

NotImplementedError: Error at d:\bld\python-igraph_1588168362456\work\vendor\build\igraph\igraph-0.9.0-pre+-msvc\src\foreign-graphml.c:1446: GraphML support is disabled, Unimplemented function call

 I have seen other people report the issue but I am still unsure of what is wrong. Any advice on how to solve would be greatly appreciated.

**Comment by vtraag** [comment]
This is correct, GraphML is not yet supported for WIndows builds. We are still working on this. Some bigger changes are being made to how `igraph` is being build, which also affects `python-igraph`. This should make building `python-igraph` in Windows easier, and also allow for GraphML support.

If this is really necessary right now, consider switching to other platforms (linux or mac). Another alternative is to use another file format for the time being.

**Comment by gclplp** [comment]
I see, thank you for the quick response.

**Comment by vtraag** [comment]
From version 0.9.1 onwards, GraphML is supported in `python-igraph` builds in `conda-forge` on all platforms, including Windows.

**Comment by vtraag** [comment]
Note that this is also supported in binary wheels of `igraph` from PyPI.
