### ISSUE TITLE
Transition from python-igraph to igraph

### ISSUE THREAD

**Issue by vtraag** [conda-forge/python-igraph-feedstock#42]
The Python interface of the `igraph` project should be installed using `python-igraph`, both using `conda` and `pip`. However, this causes some confusion for people, as they may expect `conda install igraph` to install the Python interface of the library. Similarly so for `pip install igraph`. We have been [discussing this](https://github.com/igraph/python-igraph/issues/412#issue-911490762), and we are able to transition to start using the `igraph` name on PyPI. Hence, from a certain version onwards (yet to be determined) people will be able to install the Python interface from PyPI using `pip install igraph` instead of the current `pip install python-igraph`.

Ideally, this would also become the default on `conda`, so that `conda install igraph` installs the Python interface of the `igraph` project. I believe this is also the default for all packages in `conda-forge`: they are named identical to their PyPI name. However, at the moment the [`igraph` feedstock](https://github.com/conda-forge/igraph-feedstock) provides the C core of `igraph`. The Python interface is built on top of this C core. Hence, at the moment, `conda install igraph` installs the C core. As an alternative, we could start using the name `libigraph` for the C core library, and start using `igraph` for the Python interface. That way, everything should work as people would normally expect, and would be consistent with how the package would be available from PyPI at some point in the future.

However, it begs the question of course how to deal with historical versions of the current `igraph` feedstock. Perhaps there are dependencies of some people on specific versions of the `igraph` feedstock, that expect it to provide the C core of `igraph`. It would be rather strange if below a certain version the `igraph` feedstock would provide the C core, while above a certain version it provides the Python interface. Should we simply delete all old version of the `igraph` feedstock and provide them all in the `libigraph` feedstock? That would of course be a breaking change, but the impact might be limited, if that dependency is not used too frequently?

@conda-forge-coordinator, could you please advise how we should deal with this? Do you have any prior experience with such transitions of naming of packages?

**Comment by vtraag** [comment]
@conda-forge/core could I ask your advice on the above issue?

**Comment by xhochy** [comment]
I would rather not do this. `conda` is a language independent package manager and we don't default always to have the exact same name of Python things in conda-forge as they are on PyPI. As the `igraph` package has been used before and the packages are not broken, we would also not mark them as such. This would otherwise break some people's setup. You should rather keep using `python-igraph` for the Python interface.

**Comment by vtraag** [comment]
The naming of `python-igraph` is consistent with how other package managers include the Python interface of `igraph`, so from that point of view it makes sense. My main worry was that users might be confused is they can use `pip install igraph` but have to use `conda install python-igraph`, since `conda` seems to have a more Python focus (even though it also includes some other languages). If you think this is not a problem, then let's just leave it as is indeed.
