### ISSUE TITLE
GraphML support is disabled

### ISSUE THREAD

**Issue by schierkolk** [conda-forge/python-igraph-feedstock#7]
I ran into a problem importing GraphML Files using python-igraph
```
import igraph as ig
g = ig.Graph.Tree(127,2)
g.write_graphml('test.graphml')
tree = ig.Graph.Read_GraphML('test.graphml')
```
Error:
NotImplementedError Error at foreign-graphml.c:1211 : GraphML support is disabled, Unimplemented function call

Issue may be related to lack of access to libxml2 when igraph was built. 
http://igraph.wikidot.com/installation-issues

**Comment by sodre** [comment]
@schierkolk 
Here are a couple of wrinkles around this issue:
- I can replicate your bug in Linux, as seen from the CircleCI build fail in #8. 👍 
- The test passes in my macOS notebook 👎 . I am still waiting for the result from Travis, if it fails there we have more hope to find out what is going on...
- The igraph "c" library builds and passes all the "standard" unit tests from igraph, this includes the "xml" tests, you can look at those results [here](https://circleci.com/api/v1.1/project/github/conda-forge/igraph-feedstock/15/output/13/0?file=true) 👎

**Comment by vtraag** [comment]
More recently reported in https://github.com/conda-forge/python-igraph-feedstock/issues/32, and GraphML is now supported on Windows from `python-igraph` 0.9.1. onwards.
