### ISSUE TITLE
Check ARPACK error

### ISSUE THREAD

**Issue by vtraag** [conda-forge/python-igraph-feedstock#77]
There are a few tests that show intermittent errors `ARPACK error. -- No shifts could be applied`. This issue has already been investigated before, but never resolved. This issue is to keep track of it, and try to adress it.

I will try to look up what we have done/looked at before, and link/report here whenever relevant.

**Comment by szhorvat** [comment]
I recommend trying with ARPACK 3.9.1 (but _not_ 3.9.0 which is known to have issues). CC @xylar

**Comment by xylar** [comment]
It looks like the arpack maintianers could use some help:
https://github.com/conda-forge/arpack-feedstock/pull/49
there hasn't been much recent progress.  I'm not expert enough in c/c++ libraries in general to want to volunteer.  If either of you know of anyone you could send over, that would likely really speed up how soon we could move to arpack 3.9.1.

**Comment by szhorvat** [comment]
Actually, ARPACK is a Fortran library, which makes the pool of potential maintainers even smaller.

**Comment by xylar** [comment]
Ah, yeah, I'm about equally unhelpful there.

**Comment by xylar** [comment]
Just a note that I skipped 2 more tests in #82 that were causing trouble.  We should re-enable everything (remove the patch) as soon as a new ARPACK is available.

**Comment by xylar** [comment]
Hopefully, this will finally be addressed by #87

**Comment by vtraag** [comment]
Just noting that this issue might be related to some things described in https://github.com/igraph/igraph/issues/1990.

**Comment by xylar** [comment]
Upgrading to arpack 3.9.1 didn't seem to help, see #87.

**Comment by szhorvat** [comment]
@xylar Could you please check this again with 0.11.6? See the discussion we had in #87.

**Comment by xylar** [comment]
@szhorvat, yes, so far it looks like 0.11.6 has taken care of the issues we were seeing with inconsistent testing.  I've removed the patch that was disabling some of the tests and we'll see if thing continue to work going forward.

**Comment by szhorvat** [comment]
Great, I guess this can be closed then.
